@startuml Component Diagram - Level 03
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram - Ledger System

Container(grpc_server, "gRPC Server", "grpc-go")

Container_Boundary(ledger, "Ledger System") {
    Component(api, "API", "Go", "")
    Component(usecase, "Usecase", "Go", "")
    Component(repository, "Repository", "Go", "")
    Component(probe, "Probe", "Go", "")

    Rel(api, usecase, "Uses")
    Rel(usecase, repository, "Uses")

    Rel(api, probe, "Write logs and metrics")
    Rel(usecase, probe, "Write logs and metrics")
    Rel(repository, probe, "Write logs and metrics")
}

ComponentDb(database, "Database", "Postgres", "Stores transaction and operations related to accounts")
ContainerDb_Ext(instrumentation, "Instrumentation", "New Relic", "Stores logs and metrics data. Allows monitoring.")

Rel(grpc_server, api, "Calls destiny API")
Rel(probe, instrumentation, "Write logs and metrics")
Rel(repository, database, "Write data")

@enduml
