@startuml Context Diagram - Level 01
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


title Context Diagram - Ledger System

System_Ext(transactional_systems, "Transactional systems")
System_Ext(report_systems, "Report systems")

Container(ledger_system, "Ledger", "Software System", "Allows new transactional entries to be recorded and account balance/reports queries")

Rel(transactional_systems, ledger_system, "Record transactions and query for account balances using", "rpc/https")
Rel(report_systems, ledger_system, "Query for reports using", "rpc/https")

SHOW_LEGEND()
@enduml
