@startuml Basic Sample
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

title Component diagram for Report API - Ledger system

System_Ext(report_systems, "Report systems")

Container_Boundary(ledger, "Report API") {
    Container(report_api, "Report API", "Golang exporting Rest API", "Allows systems to get syntetic and analitical data")
    Container(report_event_handler, "Event handler", "Golang exporting RPC API", "Receive events from message bus")
    ContainerDb(report_database, "Report Database", "Postgres Database", "Events related to accounts")

}

Container(message_bus, "Message Bus", "Kafka", "Transport for account events")

Rel(message_bus, report_event_handler, "Get events related to accounts", "RPC/HTTPS")
Rel(report_api, report_database, "Read and Write events related to accounts")
Rel(report_event_handler, report_database, "Store events related to accounts", "RPC/HTTPS")
Rel(report_systems, report_api, "Send analytical and summary reports requests", "RPC/HTTPS")

@enduml
