@startuml Container Diagram - Level 02
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Container Diagram - Ledger System

System_Ext(transactional_systems, "Transactional systems")
System_Ext(report_systems, "Report systems")

Container_Boundary(ledger, "Ledger") {
    Container(ledger_api, "Ledger Service", "Go", "Provides Ledger functionalities via API")
    ContainerDb(database, "Database", "Postgres", "Stores transaction and operations related to accounts")

    Rel(ledger_api, database, "Writes and reads account, entries and transactions data")
}

ContainerDb_Ext(instrumentation, "Instrumentation", "New Relic", "Stores logs and metrics data. Allows monitoring.")

Rel(transactional_systems, ledger_api, "Record transactions and query for account balances using", "rpc/https")
Rel(report_systems, ledger_api, "Query for reports using", "rpc/https")

Rel(ledger_api, instrumentation, "Write logs and metrics")

@enduml
