// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/stone-co/the-amazing-ledger/app/domain"
	"github.com/stone-co/the-amazing-ledger/app/domain/entities"
	"github.com/stone-co/the-amazing-ledger/app/domain/vos"
	"github.com/stone-co/the-amazing-ledger/app/pagination"
	"sync"
	"time"
)

// Ensure, that RepositoryMock does implement domain.Repository.
// If this is not the case, regenerate this file with moq.
var _ domain.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of domain.Repository.
//
// 	func TestSomethingThatUsesRepository(t *testing.T) {
//
// 		// make and configure a mocked domain.Repository
// 		mockedRepository := &RepositoryMock{
// 			CreateTransactionFunc: func(contextMoqParam context.Context, transaction entities.Transaction) error {
// 				panic("mock out the CreateTransaction method")
// 			},
// 			GetAccountBalanceFunc: func(ctx context.Context, account vos.AccountPath) (vos.AccountBalance, error) {
// 				panic("mock out the GetAccountBalance method")
// 			},
// 			GetAnalyticalDataFunc: func(ctx context.Context, query vos.AccountQuery, fn func(vos.Statement) error) error {
// 				panic("mock out the GetAnalyticalData method")
// 			},
// 			GetSyntheticReportFunc: func(ctx context.Context, query vos.AccountQuery, level int, startTime time.Time, endTime time.Time) (*vos.SyntheticReport, error) {
// 				panic("mock out the GetSyntheticReport method")
// 			},
// 			ListAccountEntriesFunc: func(contextMoqParam context.Context, accountEntryRequest vos.AccountEntryRequest) ([]vos.AccountEntry, pagination.Cursor, error) {
// 				panic("mock out the ListAccountEntries method")
// 			},
// 			QueryAggregatedBalanceFunc: func(ctx context.Context, account vos.AccountQuery) (vos.QueryBalance, error) {
// 				panic("mock out the QueryAggregatedBalance method")
// 			},
// 		}
//
// 		// use mockedRepository in code that requires domain.Repository
// 		// and then make assertions.
//
// 	}
type RepositoryMock struct {
	// CreateTransactionFunc mocks the CreateTransaction method.
	CreateTransactionFunc func(contextMoqParam context.Context, transaction entities.Transaction) error

	// GetAccountBalanceFunc mocks the GetAccountBalance method.
	GetAccountBalanceFunc func(ctx context.Context, account vos.AccountPath) (vos.AccountBalance, error)

	// GetAnalyticalDataFunc mocks the GetAnalyticalData method.
	GetAnalyticalDataFunc func(ctx context.Context, query vos.AccountQuery, fn func(vos.Statement) error) error

	// GetSyntheticReportFunc mocks the GetSyntheticReport method.
	GetSyntheticReportFunc func(ctx context.Context, query vos.AccountQuery, level int, startTime time.Time, endTime time.Time) (*vos.SyntheticReport, error)

	// ListAccountEntriesFunc mocks the ListAccountEntries method.
	ListAccountEntriesFunc func(contextMoqParam context.Context, accountEntryRequest vos.AccountEntryRequest) ([]vos.AccountEntry, pagination.Cursor, error)

	// QueryAggregatedBalanceFunc mocks the QueryAggregatedBalance method.
	QueryAggregatedBalanceFunc func(ctx context.Context, account vos.AccountQuery) (vos.QueryBalance, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateTransaction holds details about calls to the CreateTransaction method.
		CreateTransaction []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Transaction is the transaction argument value.
			Transaction entities.Transaction
		}
		// GetAccountBalance holds details about calls to the GetAccountBalance method.
		GetAccountBalance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Account is the account argument value.
			Account vos.AccountPath
		}
		// GetAnalyticalData holds details about calls to the GetAnalyticalData method.
		GetAnalyticalData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query vos.AccountQuery
			// Fn is the fn argument value.
			Fn func(vos.Statement) error
		}
		// GetSyntheticReport holds details about calls to the GetSyntheticReport method.
		GetSyntheticReport []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query vos.AccountQuery
			// Level is the level argument value.
			Level int
			// StartTime is the startTime argument value.
			StartTime time.Time
			// EndTime is the endTime argument value.
			EndTime time.Time
		}
		// ListAccountEntries holds details about calls to the ListAccountEntries method.
		ListAccountEntries []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// AccountEntryRequest is the accountEntryRequest argument value.
			AccountEntryRequest vos.AccountEntryRequest
		}
		// QueryAggregatedBalance holds details about calls to the QueryAggregatedBalance method.
		QueryAggregatedBalance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Account is the account argument value.
			Account vos.AccountQuery
		}
	}
	lockCreateTransaction      sync.RWMutex
	lockGetAccountBalance      sync.RWMutex
	lockGetAnalyticalData      sync.RWMutex
	lockGetSyntheticReport     sync.RWMutex
	lockListAccountEntries     sync.RWMutex
	lockQueryAggregatedBalance sync.RWMutex
}

// CreateTransaction calls CreateTransactionFunc.
func (mock *RepositoryMock) CreateTransaction(contextMoqParam context.Context, transaction entities.Transaction) error {
	if mock.CreateTransactionFunc == nil {
		panic("RepositoryMock.CreateTransactionFunc: method is nil but Repository.CreateTransaction was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Transaction     entities.Transaction
	}{
		ContextMoqParam: contextMoqParam,
		Transaction:     transaction,
	}
	mock.lockCreateTransaction.Lock()
	mock.calls.CreateTransaction = append(mock.calls.CreateTransaction, callInfo)
	mock.lockCreateTransaction.Unlock()
	return mock.CreateTransactionFunc(contextMoqParam, transaction)
}

// CreateTransactionCalls gets all the calls that were made to CreateTransaction.
// Check the length with:
//     len(mockedRepository.CreateTransactionCalls())
func (mock *RepositoryMock) CreateTransactionCalls() []struct {
	ContextMoqParam context.Context
	Transaction     entities.Transaction
} {
	var calls []struct {
		ContextMoqParam context.Context
		Transaction     entities.Transaction
	}
	mock.lockCreateTransaction.RLock()
	calls = mock.calls.CreateTransaction
	mock.lockCreateTransaction.RUnlock()
	return calls
}

// GetAccountBalance calls GetAccountBalanceFunc.
func (mock *RepositoryMock) GetAccountBalance(ctx context.Context, account vos.AccountPath) (vos.AccountBalance, error) {
	if mock.GetAccountBalanceFunc == nil {
		panic("RepositoryMock.GetAccountBalanceFunc: method is nil but Repository.GetAccountBalance was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Account vos.AccountPath
	}{
		Ctx:     ctx,
		Account: account,
	}
	mock.lockGetAccountBalance.Lock()
	mock.calls.GetAccountBalance = append(mock.calls.GetAccountBalance, callInfo)
	mock.lockGetAccountBalance.Unlock()
	return mock.GetAccountBalanceFunc(ctx, account)
}

// GetAccountBalanceCalls gets all the calls that were made to GetAccountBalance.
// Check the length with:
//     len(mockedRepository.GetAccountBalanceCalls())
func (mock *RepositoryMock) GetAccountBalanceCalls() []struct {
	Ctx     context.Context
	Account vos.AccountPath
} {
	var calls []struct {
		Ctx     context.Context
		Account vos.AccountPath
	}
	mock.lockGetAccountBalance.RLock()
	calls = mock.calls.GetAccountBalance
	mock.lockGetAccountBalance.RUnlock()
	return calls
}

// GetAnalyticalData calls GetAnalyticalDataFunc.
func (mock *RepositoryMock) GetAnalyticalData(ctx context.Context, query vos.AccountQuery, fn func(vos.Statement) error) error {
	if mock.GetAnalyticalDataFunc == nil {
		panic("RepositoryMock.GetAnalyticalDataFunc: method is nil but Repository.GetAnalyticalData was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query vos.AccountQuery
		Fn    func(vos.Statement) error
	}{
		Ctx:   ctx,
		Query: query,
		Fn:    fn,
	}
	mock.lockGetAnalyticalData.Lock()
	mock.calls.GetAnalyticalData = append(mock.calls.GetAnalyticalData, callInfo)
	mock.lockGetAnalyticalData.Unlock()
	return mock.GetAnalyticalDataFunc(ctx, query, fn)
}

// GetAnalyticalDataCalls gets all the calls that were made to GetAnalyticalData.
// Check the length with:
//     len(mockedRepository.GetAnalyticalDataCalls())
func (mock *RepositoryMock) GetAnalyticalDataCalls() []struct {
	Ctx   context.Context
	Query vos.AccountQuery
	Fn    func(vos.Statement) error
} {
	var calls []struct {
		Ctx   context.Context
		Query vos.AccountQuery
		Fn    func(vos.Statement) error
	}
	mock.lockGetAnalyticalData.RLock()
	calls = mock.calls.GetAnalyticalData
	mock.lockGetAnalyticalData.RUnlock()
	return calls
}

// GetSyntheticReport calls GetSyntheticReportFunc.
func (mock *RepositoryMock) GetSyntheticReport(ctx context.Context, query vos.AccountQuery, level int, startTime time.Time, endTime time.Time) (*vos.SyntheticReport, error) {
	if mock.GetSyntheticReportFunc == nil {
		panic("RepositoryMock.GetSyntheticReportFunc: method is nil but Repository.GetSyntheticReport was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Query     vos.AccountQuery
		Level     int
		StartTime time.Time
		EndTime   time.Time
	}{
		Ctx:       ctx,
		Query:     query,
		Level:     level,
		StartTime: startTime,
		EndTime:   endTime,
	}
	mock.lockGetSyntheticReport.Lock()
	mock.calls.GetSyntheticReport = append(mock.calls.GetSyntheticReport, callInfo)
	mock.lockGetSyntheticReport.Unlock()
	return mock.GetSyntheticReportFunc(ctx, query, level, startTime, endTime)
}

// GetSyntheticReportCalls gets all the calls that were made to GetSyntheticReport.
// Check the length with:
//     len(mockedRepository.GetSyntheticReportCalls())
func (mock *RepositoryMock) GetSyntheticReportCalls() []struct {
	Ctx       context.Context
	Query     vos.AccountQuery
	Level     int
	StartTime time.Time
	EndTime   time.Time
} {
	var calls []struct {
		Ctx       context.Context
		Query     vos.AccountQuery
		Level     int
		StartTime time.Time
		EndTime   time.Time
	}
	mock.lockGetSyntheticReport.RLock()
	calls = mock.calls.GetSyntheticReport
	mock.lockGetSyntheticReport.RUnlock()
	return calls
}

// ListAccountEntries calls ListAccountEntriesFunc.
func (mock *RepositoryMock) ListAccountEntries(contextMoqParam context.Context, accountEntryRequest vos.AccountEntryRequest) ([]vos.AccountEntry, pagination.Cursor, error) {
	if mock.ListAccountEntriesFunc == nil {
		panic("RepositoryMock.ListAccountEntriesFunc: method is nil but Repository.ListAccountEntries was just called")
	}
	callInfo := struct {
		ContextMoqParam     context.Context
		AccountEntryRequest vos.AccountEntryRequest
	}{
		ContextMoqParam:     contextMoqParam,
		AccountEntryRequest: accountEntryRequest,
	}
	mock.lockListAccountEntries.Lock()
	mock.calls.ListAccountEntries = append(mock.calls.ListAccountEntries, callInfo)
	mock.lockListAccountEntries.Unlock()
	return mock.ListAccountEntriesFunc(contextMoqParam, accountEntryRequest)
}

// ListAccountEntriesCalls gets all the calls that were made to ListAccountEntries.
// Check the length with:
//     len(mockedRepository.ListAccountEntriesCalls())
func (mock *RepositoryMock) ListAccountEntriesCalls() []struct {
	ContextMoqParam     context.Context
	AccountEntryRequest vos.AccountEntryRequest
} {
	var calls []struct {
		ContextMoqParam     context.Context
		AccountEntryRequest vos.AccountEntryRequest
	}
	mock.lockListAccountEntries.RLock()
	calls = mock.calls.ListAccountEntries
	mock.lockListAccountEntries.RUnlock()
	return calls
}

// QueryAggregatedBalance calls QueryAggregatedBalanceFunc.
func (mock *RepositoryMock) QueryAggregatedBalance(ctx context.Context, account vos.AccountQuery) (vos.QueryBalance, error) {
	if mock.QueryAggregatedBalanceFunc == nil {
		panic("RepositoryMock.QueryAggregatedBalanceFunc: method is nil but Repository.QueryAggregatedBalance was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Account vos.AccountQuery
	}{
		Ctx:     ctx,
		Account: account,
	}
	mock.lockQueryAggregatedBalance.Lock()
	mock.calls.QueryAggregatedBalance = append(mock.calls.QueryAggregatedBalance, callInfo)
	mock.lockQueryAggregatedBalance.Unlock()
	return mock.QueryAggregatedBalanceFunc(ctx, account)
}

// QueryAggregatedBalanceCalls gets all the calls that were made to QueryAggregatedBalance.
// Check the length with:
//     len(mockedRepository.QueryAggregatedBalanceCalls())
func (mock *RepositoryMock) QueryAggregatedBalanceCalls() []struct {
	Ctx     context.Context
	Account vos.AccountQuery
} {
	var calls []struct {
		Ctx     context.Context
		Account vos.AccountQuery
	}
	mock.lockQueryAggregatedBalance.RLock()
	calls = mock.calls.QueryAggregatedBalance
	mock.lockQueryAggregatedBalance.RUnlock()
	return calls
}
