@startuml Basic Sample
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

title Container diagram - Ledger system

System_Ext(transactional_systems, "Transactional systems")
System_Ext(report_systems, "Report systems")
System_Ext(external_systems, "External systems")

Container_Boundary(ledger, "Ledger") {
    Container(ledger_api, "Ledger API", "Golang exporting RPC and Rest APIs", "Allows systems to save and read transactions/events related to accounts")
    ContainerDb(database, "Database", "Postgres Database", "Reads and stores events related to accounts")
}

Container(message_bus, "Message Bus", "Kafka", "Transport for account events")

Rel_R(ledger_api, message_bus, "Sends account update events to")

Rel(ledger_api, database, "Read and write events related to accounts")

Rel(transactional_systems, ledger_api, "Save transactions, load balance and events related to accounts", "RPC/HTTPS")

Rel(report_systems, ledger_api, "Get summary and analytical data", "RPC/HTTPS")
Rel_Back(external_systems, message_bus, "Get events related to accounts", "RPC/HTTPS")

@enduml
