name: Main
on:
  - pull_request
jobs:
  Test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download dependencies
      run: go mod download

    - name: Test
      run: go get -u github.com/kyoh86/richgo && export PATH=$PATH:$(go env GOPATH)/bin && make test-coverage

  Lint:
    name: Lint job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.31

  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16

    - name: Download dependencies
      run: go mod download

    - name: Compile API
      run: make compile
