name: Release
on:
  push:
    tags:
      - v*.*.*
    branches:
      - main

jobs:
  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod vendor

      - name: Set env for tags
        if: github.ref != 'refs/heads/main'
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Set env for main
        if: github.ref == 'refs/heads/main'
        run: echo "RELEASE_VERSION=main" >> $GITHUB_ENV

      - name: Compile and Build Docker Image
        run: make REGISTRY=stoneopenbank VERSION=$RELEASE_VERSION build

      - name: Publish
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: make REGISTRY=stoneopenbank VERSION=$RELEASE_VERSION push



